version: "3.9" # Use version 3.9 of the Docker Compose file format
services:
  web:
    build: .
    command: /bin/sh -c "poetry run python manage.py migrate && poetry run python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - /app/.venv
    ports:
      - 8000:8000
    env_file:
      - ./env.dev
    networks:
      - backend
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=bookstore_dev
      - POSTGRES_PASSWORD=bookstore_dev
      - POSTGRES_DB=bookstore_dev_db
    networks:
      - backend

networks:
  backend:
    driver: bridge # Default bridge network

volumes:
  postgres_data: