name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DJANGO_ALLOWED_HOSTS: "localhost 127.0.0.1 [::1]"

    services:
      db:
        image: postgres:16
        env:
          POSTGRES_USER: bookstore_dev
          POSTGRES_PASSWORD: bookstore_dev
          POSTGRES_DB: bookstore_dev_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U bookstore_dev"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.13]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache Poetry virtualenvs
        uses: actions/cache@v4
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Copiar variáveis de ambiente
        run: cp ./env.dev .env

      - name: Esperar banco de dados
        run: |
          for i in {1..10}; do
            pg_isready -h db -p 5432 -U bookstore_dev && break
            echo "Aguardando PostgreSQL..."
            sleep 3
          done

      - name: Run migrations
        run: poetry run python manage.py migrate --noinput

      - name: Run tests
        run: poetry run python manage.py test
